### ISSUE TITLE
Feature Request: Support for additional mute conditions

### ISSUE THREAD

**Issue by zhudock** [lx-s/WinMute#1]
I'd be interested in seeing support for Mute on:
- Shutdown
- Suspend
- Logoff

Similar to [AutoMute](https://auto-mute.com/)

**Comment by lx-s** [comment]
Hey there, sorry for my late reply.
I just noticed your request.
I'll look into it :)

**Comment by lx-s** [comment]
How would you like to use those features?

As I see it, an automatic "un-mute" (after restarting/logging in/waking the device) isn't required (or even wanted) in those cases, which would make implementation much easier in that case.

**Comment by zhudock** [comment]
I agree. I'd prefer not to have the automatic un-mute on waking. My thought was if the machine is NOT muted, the suspend/sleep/logoff would mute to ensure things are muted when it wakes up again.

**Comment by lx-s** [comment]
Implemented and released as 1.5.0 :)
