### ISSUE TITLE
bug WinMute_1.7.0_prev.zip after run some days. it can't mute win10 on screen lock

### ISSUE THREAD

**Issue by ask-github** [lx-s/WinMute#11]
thanks very much

**Comment by lx-s** [comment]
I'm currently in the process of reworking the whole Mute-Logic, since in the past there were edge cases (e.g. screensaver with locking) that didn't work as expected.
Hopefully that also fixes this problem.

**Comment by ask-github** [comment]
thanks
really appreciate for your works

**Comment by lx-s** [comment]
Please try the new 1.9-release: https://github.com/lx-s/WinMute/releases/tag/1.9.9
