### ISSUE TITLE
1.6.0: doesn't work after Windows reboot, needs to be restarted manually

### ISSUE THREAD

**Issue by SandroGaehler** [lx-s/WinMute#12]
I added WinMute to the autostart path, and it also starts automatically with Windows (icon visible in tray). However, it does not work until I manually exit and restart it. Is there a debug console or something that I could use to help me locate the issue?

1.6.0 on Windows 10 10.0.19044, Build 19044, x64

**Comment by lx-s** [comment]
Please try the new 1.9-release: https://github.com/lx-s/WinMute/releases/tag/1.9.9
