### ISSUE TITLE
Bluetooth trigger is triggered when bluetooth quick settings menu is open

### ISSUE THREAD

**Issue by Rediwed** [lx-s/WinMute#15]
Hi! On Windows 11, it appears that the bluetooth trigger is triggered whenever you open the bluetooth quick access menu (even if the headset is still connected and active).

Steps to reproduce
1. Have the bluetooth trigger active
2. Listen to some music / audio
3. Access the W11 quick settings and click on the rightward arrow in the bluetooth icon
4. The audio will get muted

**Comment by lx-s** [comment]
Hi!

This one will be tough, as I don't have any Windows 11 supported :/
I'll try to set up a VM with Bluetooth passthrough, to reproduce it!

**Comment by lx-s** [comment]
Couldn't install a W11 VM with bluetooth passthrough, but could reproduce it on Windows 10.

As soon as scanning for new devices starts, Windows sends a lot of Bluetooth messages, which WinMute did not interpreted correctly. 
[I changed the detection logic for this case](https://github.com/lx-s/WinMute/commit/d9dd49d9170ac3660bfd6b08af4bb29b181fedba). In my quick tests it worked, but I'd appreciat it, if you could give it a go yourself, before I release this version.

Thanks in advance :
[WinMute_1.2.2-beta.zip](https://github.com/lx-s/WinMute/files/9400926/WinMute_1.2.2-beta.zip)
)

**Comment by Rediwed** [comment]
I've just tested your latest release, and the issue appears to be fixed! There was also an issue resulting in the same effect when sitting in the waiting room of a Teams meeting. That issue also appears to be gone. I'll test it some more.
