### ISSUE TITLE
Mute specific application from volume mixer

### ISSUE THREAD

**Issue by RealCodaholic** [lx-s/WinMute#2]
Hi, this is a great app, however can it be modified to mute specific application like google chorme only  in the volume mixer?

**Comment by lx-s** [comment]
Hey there, I understand your feature request, and I can see how this would be useful to some people.

I could imagine a simple "blocklist" where a user can add the name/path of programs, and if those names are present in the volume mixer, those programs will get muted.

I'll toy around with your idea, when I have a little more spare time :)

**Comment by lx-s** [comment]
Hi there, seeing as I have very little time, I am afraid that I can not concentrate on this feature.
I'll keep WinMute as a "mute all or nothing" app for now. If you have the time and energy you can propose a pull request and I could merge it, if it works :)

**Comment by Abba-** [comment]
If this is something someone decides to take a crack at, please remember how simple this application is to use
.
An example use case for me is when I'm in a Zoom Call (or Meet, so maybe needs to check by Windows title), I'd want to mute specific other windows.  This might need a different trigger or other shortcut (if Windows title has X Mute Y). Overall I can imagine this settings being the type of thing people will want granular control over, but would need be done carefully to not spoil simplicity.

To be clear this is something I would love to see, I just want to warn those that approach this that it might take some though beyond just simply muting specific windows...
