### ISSUE TITLE
Never unmutes if reboot before quite hours ends

### ISSUE THREAD

**Issue by VorlonCD** [lx-s/WinMute#22]
My quite hours are set to end at 8:30 am.  If I happen to reboot before 8:30, my machine stays muted until I manually unmute.

So maybe:

If app Initializing AND QuiteHours is enabled AND NOT IsQuietTime AND IsMuted:   Unmute

You would have had a pull request if it was in C#  :)

Great little program!  I had been using Volume² before I found this gem but its not open source and I believe its author is Russian.

**Comment by lx-s** [comment]
Thanks! I'll get on it within the next few days :)

**Comment by VorlonCD** [comment]
Thanks!  I've had that setting on for a while and haven't noticed the issue.
