### ISSUE TITLE
Suggestion: Time Delay

### ISSUE THREAD

**Issue by nahventure** [lx-s/WinMute#24]
I actually use my pc for work mostly, and I have most apps setup to start sending mobile noti after 5 mins of inactivity. 

Can we some how have it mute after 5 minutes after the screen locks? (Option to configure it would be great)
I guess it could work for manual lock too.

**Comment by lx-s** [comment]
Interesting, albeit very niche (i guess) suggestion.
But that should be a fairly simple addition, so I'll integrate it when I get around :)

**Comment by lx-s** [comment]
This should do the trick. As always, I'll let it stew for a few days before publishing a release.
If you want to test it in the meantime, please go ahead :)
[WinMute_2.3.1.0_WithDelay.zip](https://github.com/lx-s/WinMute/files/12559149/WinMute_2.3.1.0_WithDelay.zip)
