### ISSUE TITLE
Memory access exception with version 2.4.0 when restarting Windows

### ISSUE THREAD

**Issue by MovieWiz** [lx-s/WinMute#25]
I have up-to-date Windows 10 Home.  I used the Winmute's zip file to put the program on my hard drive (i.e., no installer).  I have the option set to autostart winmute when Windows starts.  Other than that, all settings are the default ones.

When I try to restart Windows, Winmute displays an error message about an illegal memory access.  This interferes with the timely restarting of Windows.

Went back to version 2.3.1 and the problem does not happen.

Hope this helps.  Great program, by the way!!!

**Comment by lx-s** [comment]
Thanks for your report!

It is fixed in https://github.com/lx-s/WinMute/releases/tag/2.4.1.0
