### ISSUE TITLE
Add italian language to GUI

### ISSUE THREAD

**Issue by bovirus** [lx-s/WinMute#26]
@lx-s 

Could you pelase modify source code to add Italian language?

Could you pelase move all strings usen in 'WinMute.rc' in a separate 'WinMute.resx' file?
Then you can translate using 'WinMute.de.resx' for German and 'WinMute.it.resx' for Italian)

I can help translating it in Italian.

Thanks

**Comment by lx-s** [comment]
Hey there, currently WinMute is not at all prepared for multi language.
But I can plan this feature for the next release and start working on it :)

When I have the infrastructure in place, I'll gladly get back to you for the italian translation.

**Comment by bovirus** [comment]
@lx-s 

Thanks for you reply.
When the language files will be ready I will create the italian language.

**Comment by sal0max** [comment]
A great free platform for collaborative translations is the Weblate instance on Codeberg 🙂

https://translate.codeberg.org/

**Comment by lx-s** [comment]
@bovirus Then I'll get onto it as soon as possible :)

@sal0max thanks for the tip! I'll try if I can export it to a Windows/C++/DLL format thingy I need for Windows.

Currently I was living my c++ life blissfully ignorant in regard to i18n ;)

**Comment by sal0max** [comment]
👍 

I'm sure you find a supported format, suitable for your project 😄 
https://docs.weblate.org/en/latest/formats.html

**Comment by bovirus** [comment]
@lx-s 

Weblate it a good iddea.
In this  way you can separate source code development/changes from language updates.

**Comment by bovirus** [comment]
@lx-s 

Have you any date for the plan to add multilanguage GUI?

**Comment by lx-s** [comment]
> Have you any date for the plan to add multilanguage GUI?

I am currently working on it, whenever I can spare the free-time (work and family life is like pacman munching all my free-time dots ;)).
I have already started the work on branch 26_i18n and tag all commits with this Issue, so you can see whenever i push something new. I will try to work on it steadily the next few weeks.

My personal goal is: Somewhere around november.

Sorry for the wait. I appreciate your help!

**Comment by lx-s** [comment]
To give you a short ping: I finished translating all the strings within the source code and the tray menu.
Next step are the dialog ressources.

**Comment by bovirus** [comment]
@lx-s 

Thanks for your job.

**Comment by lx-s** [comment]
Good news! Everything is now translatable and I have already translated it to german.
The next few days I'll see how this weblate thingy works and try to integrate it :)

**Comment by bovirus** [comment]
@lx-s 

Thanks.
When you will ready plwase post the weblate link to translate your project.
When at least one translation will be ready for me you can create an test version to test the programn with translation.

**Comment by lx-s** [comment]
I added the project, but it's not really recognizing the rc files:

https://translate.codeberg.org/projects/winmute/

I'll try to fight with it a bit more, but if it doesn't work, I'll do it in a different way

**Comment by lx-s** [comment]
If you want to start nonetheless, just copy the `Translations/wm_de/` folder to `Translations/wm_it/`,
rename the files accordingly and start editing :)

The english source material is located at `Translations\wm_en\wm_en.rc`

**Comment by lx-s** [comment]
Alright, since I can't get this weblate-thing to work, we have to do it the straight forward way.

I added a branch for you (named `i18n_italian`) to work on.
Just give me a Pull Request for this branch, when you are finished!

Thank you :)

**Comment by lx-s** [comment]
Alright, scratch everything I said.

I thought about it and scratched the whole way I did translations and reworked the whole thing.
Now, the translations are done with json files.

What you can do now is:
1. Download this [winmute_beta_i18n.zip](https://github.com/lx-s/WinMute/files/13696211/winmute_beta_i18n.zip)
2. Copy the `lang/lang-en.json`, rename it to `lang/lang-it.json` and translate it.
3. Send me a PR or attach it here.

In the next few days I'll see if I can make weblate recognize that format ;)
But even if not, It's a lot easier to deal with the json files instead of the Windows Resource Files, at least for this kind of project.

**Comment by bovirus** [comment]
@lx-s 

Thanks for the translation option.
I completed the Italian tarnslation.

Some proposals about language

- Enable in the translation project the option to re-use same translation (now report as warning).
- Disable in the project the check of new lines (see after).
- Please check that multiperiod string have each period on separate line.
- Check thath multiperiod string end with ".". There is a multiperiod string without "." at the end.
- Replace "workstation" with" computer" (more generic)
- Don't use "your"/"Your" in string. Sounds more generic.
-  Use always "Bluettoth" and not "bluetooth" (it's own name).

Multiperiod strings without . at the end

WLAN is not available or disabled. WLAN muting will be disabled on this computer

Thanks.

**Comment by lx-s** [comment]
Thank you so much for all the infos!

I made the base english file also editable by translators (seeing as I am not a native speaker, someone might contribute better text) :)
I also tried to implement all your suggestions.

> Please check that multiperiod string have each period on separate line.
> Check thath multiperiod string end with ".". There is a multiperiod string without "." at the end.

What do you mean by that?

> Add a note for "English" string that is the language name and should replace with specific language name.

I added a comment - is that what you meant or is there a better way to do it in weblate?

**Comment by bovirus** [comment]
@lx-s 

I translated "English" in Italian but after I undeerstood that is the specfic language name.
Then it's important that someone started a new translation this is the language name.

Question: in which path/file are saved WinMute settings?

**Comment by lx-s** [comment]
> I translated "English" in Italian but after I undeerstood that is the specfic language name.
> Then it's important that someone started a new translation this is the language name.

Yeah, I understand - I added the explanation to the two meta fields. They appear in the right sidebar of weblate. Hopefully that helps :)

> Question: in which path/file are saved WinMute settings?

WinMute saves its settings into the Registry:  https://github.com/lx-s/WinMute/blob/dev/WinMute/WMSettings.cpp#L39

**Comment by bovirus** [comment]
@lx-s

WLAN is not available or disabled. WLAN muting will be disabled on this computer.

add new line

WLAN is not available or disabled. 
WLAN muting will be disabled on this computer.

These string for uniformity hould have same starting letter (uppercase or lowercase9 and not point at the end because are menu option or settings

... Computer is locked
... Screen turns off

**Comment by bovirus** [comment]
Please this GUI issues

Now
![image](https://github.com/lx-s/WinMute/assets/1262554/32dc7dff-18b1-46f6-a35a-90af5808af47)
Proposal
![image](https://github.com/lx-s/WinMute/assets/1262554/dd3c48e6-1b24-436f-9d3c-d81e79f20740)

Now
![image](https://github.com/lx-s/WinMute/assets/1262554/901e23f1-3776-47d8-b215-0c1553813a66)
Proposal
![image](https://github.com/lx-s/WinMute/assets/1262554/d58a76c4-9c90-41cc-a3d1-5bfbc35cdd15)

**Comment by bovirus** [comment]
@lx-s 

"Mute on (no volume restore)"

should be

"Mute on (no volume restore) when..."

**Comment by bovirus** [comment]
@lx-s 

Endpoint = Device?

To respect uppercase/lowercase and no "." at the end of menu or setting explanation please change in english language

... Computer is locked. -> ... computer is locked
... Screen turns off. -> ... screen turns off
... Shutdown -> the computer shuts down
... the computer is locked. -> ... the computer is locked
... the screen turns off. -> ... the screen turns off
... the computer shuts down. -> ... the computer shuts down
... the computer goes into sleep/hibernate. -> ... the computer goes into sleep/hibernate
... the user logs out. -> ... the user logs out
... when WinMute is started within a RDP session. -> ... WinMute is started within a RDP session

Thanks.

**Comment by lx-s** [comment]
Done, done and done. We are getting there bit by bit ;)

GUI work I have to do a bit later - but i'll definitely check with all the languages

**Comment by lx-s** [comment]
Changed dialog spacings

[winmute_beta_i18n.zip](https://github.com/lx-s/WinMute/files/13702682/winmute_beta_i18n.zip)

**Comment by lx-s** [comment]
Alright, Weblate is now setup so I can comfortly pull and push the new language strings.

Sorry for any intermittent locks of the translation repo.

**Comment by bovirus** [comment]
@lx-s 

Thanks for new beta

Please check UI proposal

- Now
![image](https://github.com/lx-s/WinMute/assets/1262554/cd105315-34b2-4e79-a8b2-b08e073bdf66)

- Proposed
Increase list box height
Move burton group on down (centered on box height) 
Move button goup a few on right to have on left and right of the buuton same empty space
![image](https://github.com/lx-s/WinMute/assets/1262554/f36ece3b-a746-44b5-b3ae-fcbce12f7140)

**Comment by lx-s** [comment]
The problem with moving 

> * Now
>       ![image](https://private-user-images.githubusercontent.com/1262554/291306593-71e9541f-0ca3-4c7f-99eb-6a8a2344ab02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDkwMjUsIm5iZiI6MTcwMjkwODcyNSwicGF0aCI6Ii8xMjYyNTU0LzI5MTMwNjU5My03MWU5NTQxZi0wY2EzLTRjN2YtOTllYi02YThhMjM0NGFiMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMTQxMjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmMxMzJmMmQ5ODM4MzFjZDg0YmVjYmM2ZmQ3N2VjOTU4MzAzNDNiOWVhNGEzZDQ5OTQyZjVhNTMzNWIzMjU2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8YyUq9I_YcP2iQylFUC2UrbjMCFm7yEqnVGMzTwakMo)

Moving the checkbox up works for italian language, but would not work for the german language.
I'm thinking about moving the second checkbox under the list, but currently the spacing is there to space it right for english, german and italian.

I am not really satisfied with it myself

**Comment by lx-s** [comment]
My proposal:

- ![grafik](https://github.com/lx-s/WinMute/assets/411211/cd65e522-8182-41d3-8b86-56b80f90e1aa)
- ![grafik](https://github.com/lx-s/WinMute/assets/411211/31513369-66d9-4039-9cb0-8e4a0b3fc79a)

**Comment by bovirus** [comment]
@lx-s 

For me are ok.
But it's better move a few button grpup on right and have some empty space on left/right the buttons

![image](https://github.com/lx-s/WinMute/assets/1262554/aea6dc44-f966-4682-9958-abf0848808a7)

**Comment by lx-s** [comment]
Small Update for you
[winmute_beta_i18n.zip](https://github.com/lx-s/WinMute/files/13705677/winmute_beta_i18n.zip)

Since the translation infrastructure is now complete, I'll start working on those other tickets for the 3.0 release :)

**Comment by bovirus** [comment]
@lx-s 
Thanks.
last questiuon: when you talk "endpoint" does it mean "audio device"?

**Comment by bovirus** [comment]
@lx-s 

I think that if you use "device" or "audio device" instead "3ndpoint" for most users will be better.

**Comment by lx-s** [comment]
> I think that if you use "device" or "audio device" instead "endpoint" for most users will be better.

Changed it. Also some new strings were added because of a new update check feature.
I'll close this issue, since the main thing "add italian language" is now done :).
If you happen to stumble further layout problems or have suggestions for the wording please open another ticket for that specific problem.

Thanks again for all your help!
