### ISSUE TITLE
Inno Setup installer script improvement

### ISSUE THREAD

**Issue by bovirus** [lx-s/WinMute#27]
@lx-s 

Could you please add italian language to instalelr.
hat version of InnOS etup instalelr are you using.

Pelase check screenshot

![image](https://github.com/lx-s/WinMute/assets/1262554/b66a93f7-e4c6-4748-8f84-fbc372822e43)

Is missing File version and copyright info.

About copyright version is important company name and staring and ending copyright year.
Ending copyright year can get via date functiona nd automatically update.

Name: "autostart" ; Description: "Start WinMute when you log on" ; GroupDescription: "Autostart"; Flags: unchecked

Thie "description" string is untranslated.
Please add it in Custom string.

I propose to move language and custom strings in a separate .iss file (and use #include in original .iss file to include it).
In this way teh main script is untocuehd and any additional language changes are only in custom string file.

If you agree I can made all changes.

In Window program list is not sued program icon (use genric text icon).

![image](https://github.com/lx-s/WinMute/assets/1262554/942b7ffa-147e-46cf-95e4-55630e66b9fa)

**Comment by lx-s** [comment]
If you want, you can make a pull request :)

**Comment by bovirus** [comment]
@lx-s 

Some request about improvemt.

- Copyright

For copyright message just put current year or do you want a year interval. ex

(c) 2203 LX-Systems
(c) 2017-2023 LX-Systems

In prefer second option wht's the starting copyright year?

- Info-before
I propose to use this (new line for each paragraph)

[info-before.txt](https://github.com/lx-s/WinMute/files/12776892/info-before.txt)

Could be possible to sue a info-before in italian for italian lnaguage?

- License
 
For license I propose to format not it to 80 chars line. Like this

[license-new.txt](https://github.com/lx-s/WinMute/files/12776887/license-new.txt)

Can be possible use for Italian language a localized version of the license?

Thanks.

**Comment by lx-s** [comment]
> * Copyright

2011-`<current date>` 

> Info-before

👍

> [license-new.txt](https://github.com/lx-s/WinMute/files/12776887/license-new.txt)

For the source code and the root LICENSE file, i prefer the 80 column version, as that is the cannonical it is written.
Is that a problem for the installer? Afaik other projects show it also like this during the setup.

> Can be possible use for Italian language a localized version of the license?

If you can find an official version of the license, otherwise i'd prefer it to be the original english text.
As far as I can tell, there is no official version of the license for different languages (I also looked for a german version, but couldn't find one).

**Comment by bovirus** [comment]
@lx-s 

- Copyright years.

Thanks.

- License text layout

Personallly for the 80chars layout is not mdoern.
Was OK in the past for terminal layout (80x25).
Is not the best one for current format for modernn license page.
Pleaseecheck how can be with original and new mdoern layout without 80chars limitation.

- Original

![image](https://github.com/lx-s/WinMute/assets/1262554/afbd1002-8c2f-4798-a7a5-1ab4fb461a81)

- New layout (not limited to 80 chars).

![image](https://github.com/lx-s/WinMute/assets/1262554/988368ca-4e9b-4449-a4a8-ad5cbb215655)

All sapce sued.
Easier to read (no forced new lines).
New line to separate pragraph.

- Localzied license.
For the license please consider by user point of view.
To accept the license (just not to press OK) the suer should understand the "license agreement" ad then should be in local language (not all suer know english).
Otherwise for many user that doesn't know english is just press "OK" to go away.
 
- Info-before.txt localization

What's about "info-before.txt"?
Coudl be localized?

**Comment by lx-s** [comment]
Hey there, i just merged your PR.
Thanks for the work!

The next update for winmute will contain your setup changes, as well as the new translation infrastructure (that I am currently (slowly) working on).

**Comment by bovirus** [comment]
@lx-s 

Thanks a lot.
