### ISSUE TITLE
[REQ] Please mute the sound even when the monitor is manually turned off.

### ISSUE THREAD

**Issue by splash70** [lx-s/WinMute#32]
This is a request, not a issue, so I'm sorry if it is not appropriate to write here...

Winmute works when Windows turns off the monitor, but not when the monitor is manually turned off.
For example, with the HDMI connection, Windows can monitor the status of the monitor, so could you please make it work even if the monitor is manually turned off?

Thank you.

**Comment by lx-s** [comment]
Don’t worry - this is the place to request a feature :)
I’ll look into it!

**Comment by lx-s** [comment]
Alright, unfortunately the apparently simple things aren't most of the time.

There is apparently no way in the Windows API to get notified when a display is disconnected. 
For reference, see [Is there any way to detect the monitor state in Windows (on or off)?](https://stackoverflow.com/questions/203355/is-there-any-way-to-detect-the-monitor-state-in-windows-on-or-off) on Stackoverflow.

The only thing I could implement would be a busy loop that checks every few seconds if the display is off (via [GetDevicePowerState](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getdevicepowerstate?redirectedfrom=MSDN)), but this goes against my rule, that I want to do everything by notification and not by waking the device every few seconds.

If I would do it via a busy check, then either:
 - the time frame would be too large and it might cause a significant lag between display off and sound off
 - the time slice is too small and WinMute might unneccesarily Tax CPU and battery by busy waiting on something, that might rarely happen.

 When I stumble upon a better way to do it, I'll reopen this issue. For now I have to close it though :(
