### ISSUE TITLE
2.5.0 - Installer - Issue with accented letter

### ISSUE THREAD

**Issue by bovirus** [lx-s/WinMute#33]
@lx-s 

Please check screenshot

![image](https://github.com/lx-s/WinMute/assets/1262554/02fe07a4-e986-484b-9a4d-12825ab18669)

What version of instalelr amker are you usinG?
The language file with custom strings is ANSI or IUTF8?

**Comment by bovirus** [comment]
@lx-5

Please fix in next buiild.

**Comment by lx-s** [comment]
Fixed :)
![grafik](https://github.com/user-attachments/assets/9df5b841-1a5b-4ad2-9c5c-6e950e0bd54c)
