### ISSUE TITLE
Typo in English translation

### ISSUE THREAD

**Issue by eanema** [lx-s/WinMute#36]
I noticed a typo in the English translation file, line 47: https://github.com/lx-s/WinMute/blob/9c4478eeaccc714b82f09d60155aa46b2e4e9720/Translations/lang-en.json#L47

'of' should be 'off'

**Comment by lx-s** [comment]
Thanks! I fixed it https://translate.codeberg.org/translate/winmute/winmute/en/?q=traymenu.mute-on-screen-suspend&sort_by=-priority%2Cposition&checksum=

Will be in the next release :)
