### ISSUE TITLE
Feature request: Option to not automatically unmute when screen turns on during quiet hours

### ISSUE THREAD

**Issue by michael-milette** [lx-s/WinMute#37]
My computer screens will occasionally turn on briefly at night during quiet hours. Other times, I will start using my computer during quiet hours. Both of these scenarios turn on the screen which unmutes the speakers. 

What I would like is a new checkbox setting, something like: "Do not automatically unmute during quiet hours.". When this option is enabled, the only way to unmute audio during quiet hours would be to do so manually. And, if you then lock the computer, the audio would be muted again respecting quiet hours.

The only alternative I have found is to use the "Mute all devices" option in WinMute. However, this is usually after I access some web page that has sound/audio causing me to panic during quiet hours.

I wish I had come across WinMute years ago. Something like this should be included with Windows. Thank you for sharing this useful tool with the world.

Please let me know if you have any questions.

Best regards,

Michael Milette

**Comment by lx-s** [comment]
Hi there!

 WinMute should absolutely not unmute during quiet hours.
My vacation starts tomorrow but I’ll take a look it at right afterwards :)

**Comment by lx-s** [comment]
With this build I cannot reproduce the problem.
Would you mind trying it out, before I put together a release?

[WinMute_qh_fix_37.zip](https://github.com/user-attachments/files/15544080/WinMute_qh_fix_37.zip)

**Comment by michael-milette** [comment]
Hi @lx-s ,

Thanks for the preview. I did my first test which is:

1) Right-click on the WinMute icon and select **Mute All Devices** to enable it.
2) Confirm that all devices are muted.
3) Press CTRL-L to lock Windows.
4) Wait for the screen to turn off.
5) Press a key to wake up the screen.
6) Log into Windows.
7) Right-click on the WinMute icon and notice that **Mute All Devices** is still checked.

However, the devices are not muted. This is the issue. I don't think that it should be unmuting itself.

The issue with the devices unmuting themselves if I wake up my screen during the scheduled mute time (instead of a forced mute) is similar except that the scheduled quiet time triggered the muting of all devices instead in step 1. The outcome is the same, the output devices are all unmuted when I log back in.

Just so that we are working on the same page and I am not misunderstanding the functionality of the settings, here are a couple of screenshots of my settings:

<img width="304" alt="image" src="https://github.com/lx-s/WinMute/assets/3808579/4b678934-b038-41e0-bcc4-1e2fe07bccec">

<img width="304" alt="image" src="https://github.com/lx-s/WinMute/assets/3808579/516ce868-1517-42eb-ad5a-d637aa1c4b6e">

On a side note, **Mute All Devices** option in the right-click menu does not have a checkmark beside the option when all devices are muted by the Quiet Time setting. Not sure if this is by design or not. As a result, if I want to unmute all devices during quiet time, I need to use this option twice. I expected it to be checked anytime the tool mutes all devices, whether manually or automatically.

Best regards,

Michael

**Comment by lx-s** [comment]
Ah yes.. I see the confusion.

"Mute all devices" should only be a "one shot mute everything" but no permanent setting.
This wouldn't work anyhow, as I would have to prevent all other processes from unmuting (which would be do able, but pretty user hostile).
I'll remove the checkmark and clarify the wording of the option, as the checkmark makes no sense whatsoever.

If you have configured "quiet hours" in the settings however, WinMute should respect this setting and not unmute, even when the screen goes on.
WinMute will however not prevent you from unmuting your system manually.
