### ISSUE TITLE
Can't Save Mute Only Device

### ISSUE THREAD

**Issue by djarbz** [lx-s/WinMute#38]
**Describe the bug**
I am attempting to specify which device should be muted.
The save button never enables.

**To Reproduce**
Attempted both running normally and as administrator.
1. Open WinMute Settings
2. Select the `Mute` tab
3. Check `Manage audio devices individually`
4. Click `Manage devices...`
5. Ensure `Mute only listed devices` is selected
6. Click `add`
7. Select my device (or any device) from the dropdown
8. Save is not enabled to confirm my selection

**Expected behavior**
I should be able to select my device and add it to the whitelist.

**Screenshots**
![image](https://github.com/lx-s/WinMute/assets/30350993/64362be2-2232-4d29-aecb-a72c14cc36b8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.5.1.0

**Additional context**
I am also using VoiceMeeter Banana to route my audio.

**Comment by lx-s** [comment]
Fixed the problem. I'll take a look at the other issue and prepare a release afterwards.

In the meantime, you can use the attached build, if you want :)
[WinMute_fix_save_button.zip](https://github.com/user-attachments/files/15543661/WinMute_fix_save_button.zip)

**Comment by lx-s** [comment]
Fixed the problem. I'll take a look at the other issue and prepare a release afterwards.

In the meantime, you can use the attached build, if you want :)
[WinMute_fix_save_button.zip](https://github.com/user-attachments/files/15543661/WinMute_fix_save_button.zip)

**Comment by djarbz** [comment]
Thank you!

**Comment by benjamin-stern** [comment]
This is still an issue when can we have a release? @lx-s ... This has been fixed almost 6 months ago.

**Comment by lx-s** [comment]
You are absolutely right. Sorry for the huge delay.
I just carved out some time and made a release with the latest smaller fixes (as well as french language support) :)
