### ISSUE TITLE
[enhancement] Pause Music/Video thats playing

### ISSUE THREAD

**Issue by BedBug2479** [lx-s/WinMute#39]
is it possible to pause the apps like Spotify/Video Players/etc along with Mute?

**Comment by lx-s** [comment]
[I've looked into this some time ago](https://github.com/lx-s/WinMute/issues/7#issuecomment-1096446375).

Unfortunately it is not really feasible to implement... But I'll keep my eyes open, if I ever come across a good solution.

Sorry for now :(
