### ISSUE TITLE
WinMute 2.5.1 - Installer issue - Icon in Program list is a generic icon

### ISSUE THREAD

**Issue by bovirus** [lx-s/WinMute#40]
@lx-s 

**Describe the bug**
INn Windows Program list the line about WinMute has a genric icon (not dedicated icon)

**To Reproduce**
1. Installa WinMute 2.5.1
2. Go in Windows Program List
3. Check line about WinMute

**Expected behavior**
Check Inno Setup .iss file to fix this.

**Screenshots**
![image](https://github.com/user-attachments/assets/a07c40f9-b093-4fb2-a8ce-0c80de78b0ea)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22 H2 64bit Italian

**Additional context**

**Comment by lx-s** [comment]
This one is a real headscratcher that I noticed too, because I should have set everything that is needed for innosetup to create the proper entry in Windows.

I'll look at it again, when my private and professional schedule clears up :(
