### ISSUE TITLE
[Request] Cmdline Parameter / Mute & Exit

### ISSUE THREAD

**Issue by DennisGaida** [lx-s/WinMute#8]
WinMute is a nifty little tool!

I would love to start it with Windows and mute system volume **on boot**. I mean that could be an option in the app, but it would help me if I had a commandline parameter such as /mute --muteandexit so I could put this in Autostart and it just mutes the system on boot. I don't actually need to have it running in the background because all I want is a silent system on boot.

**Comment by lx-s** [comment]
Why not :)

Noted!

**Comment by lx-s** [comment]
Instead of a command line parameter, here is a new tool for you: https://github.com/lx-s/Mute/releases/tag/0.1 ;)

**Comment by DennisGaida** [comment]
Awesome! Don't know whether I'd rather have this integrated in this existing tool, but it works flawlessly.
